### ISSUE TITLE
config.sys GUI

### ISSUE THREAD

**Issue by JoeMejica** [gve-sw/MerakiMVMandMXAnalyticsDemo#2]
1) Create a GUI front end for the config.sys file to make it user friendly. 

2) Create DB table to store values and have app query table.

**SUB-TASKS**
- [x] Create Branch
- [x] Create HTML template
- [x] Update flaskApp.py with route
- [x] Update base.html to include setup icon
- [x] create DB table to store config.py variable values
- [x] write logic to query db to populate variables
